version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: myabeka-mongo
    restart: unless-stopped
    env_file:
      - ../.env.mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: myabeka-mongo-express
    restart: unless-stopped
    env_file:
      - ../.env.mongo
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-example}@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USER:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASS:-admin}
    ports:
      - "8083:8081"
    depends_on:
      - mongo

volumes:
  mongo-data:
